name: CI

on: [push, pull_request]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install terraform
        uses: marocchino/setup-terraform@v1
        with:
          version: "0.13.0"
      - name: Initialize Terraform
        run: cd src/ && terraform init -backend=false
      - name: Validate syntax
        run: cd src/ && terraform validate
      - name: Check format
        run: cd src/ && terraform fmt -check -recursive
